language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

addons:
  postgresql: 9.3

env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/jsonpgpfield

before_script:
  - psql -c 'create database jsonpgpfield;' -U postgres

install:
  - pip install django==1.8.2 psycopg2==2.5.4

script: python setup.py test

notifications:
  email:
    recipients:
      - tombooth@gmail.com
